name: base_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔑 Secure credential storage
  flutter_secure_storage: ^9.0.0

  # ⚡ Lightweight storage for flags like isLoggedIn
  shared_preferences: ^2.2.3

  # Add this line
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/background.png